* Why and what

  Shell scripts are everywhere and working with them can be challenging.  Let's try to
  make shell scripting saner by accumulating knowledge here.


* How

  Scripts written using these [[file:mod/][models]]:

    - fail as soon as a command fails to guard against failure escalation
    - print error messages telling what went wrong, in which script, when and the
      command that failed to help identify problems.
    - offer a way to step trough commands
    - they prevent undefined variables to be used to guard against things like ~rm -r
      $undefined/~ getting understood by ~bash~ as: ~rm -r /~
    - offer a way to clean the state of the program after exit and even after an error
    - are relocatable i.e. independent from a given filesystem i.e. you can install
      them anywhere
    - interpreter can be specified at install time which makes them usable on more
      systems
    - …

  Workflow:

    1. need a new script
    2. copy/paste ./mod/script_model
    3. implement using ./lib/*


* Install

  #+begin_src sh
    git clone https://github.com/phfrohring/bash.git
    cd bash
    ./install ~/bash
    ~/bash/bin/test_script
  #+end_src


* Contributing

   Contributions are welcome.

   See: [[https://phfrohring.com/note?id=1544733b-803b-4d57-b72f-31cb57304f8a][Collective Code Construction Contract]]


* License

  [[file:LICENSE][MPLv2]]


* Coding style

  [[file:coding_style.org][Coding style]]


* Resources

  - [[https://github.com/jlevy/the-art-of-command-line][The Art Of Command Line]]
  - [[https://github.com/alebcay/awesome-shell][Awesome Shell]]
  - [[http://redsymbol.net/articles/][Aaron Maxwell]]
  - [[https://github.com/koalaman/shellcheck][ShellCheck]]
  - [[https://dwheeler.com/essays/filenames-in-shell.html][Filenames In Shell]]
  - [[https://google.github.io/styleguide/shell.xml][Google Shell Style Guide]]
  - [[https://wiki.bash-hackers.org/][Bash Hackers]]
  - [[http://mywiki.wooledge.org/][Greg's Wiki]]
  - [[http://tldp.org/HOWTO/Bash-Prog-Intro-HOWTO.html#toc][BASH Programming]]
  - [[http://www.tldp.org/LDP/abs/html/][Advanced Bash-Scripting Guide]]
